{% set name = "root" %}
{% set version = "6.16.00" %}
{% set hash = "c8415df5a0ec1619df5da0a2a36d79a47f1cf5927ee66cb5f045b39bb250c79a" %}
{% set variant = "openblas" %}
{% set clang_version = "5.0.0" %}
{% set clang_patches_version = "6.16.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/root-project/root/archive/v{{ version|replace(".","-") }}.tar.gz
  sha256: {{ hash }}
  folder: root-source
  patches:
    - patches/root-x.xx.xx_cling-runtime-sysroot.patch
    - patches/root-6.18.00_root_config_cxxstd_flags.patch
    - patches/root-6.16.02_allow_setting_clang_version.patch  # [osx]
    - patches/root-6.16.02_not_test_cxx11_clang_4.patch  # [osx]
    - patches/root-x.xx.xx_python_mac_os.patch  # [osx]
    - patches/root-x.xx.xx-copy-abspath-headers.patch  # [osx]
    - patches/root-x.xx.xx-osx-remove-hardcoded-sysroot.patch  # [osx]

build:
  number: 6
  skip: True  # [win]
  features:
    - blas_{{ variant }}
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=root
    - {{ pin_subpackage('root', max_pin='x.x.x') }}
  ignore_prefix_files:
    # FIXME: Figure out how to correct the paths in the PCH
    - etc/allDict.cxx.pch  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - git
    - pkg-config
  host:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - afterimage
    - openblas
    - cfitsio
    - clangdev={{ clang_version }}
    - clang_variant * cling_{{ clang_patches_version }}
    - davix
    - fftw
    - freetype
    - giflib
    - gsl
    - gdk-pixbuf
    - krb5  # [osx]
    - libglu  # [linux]
    - libpng
    - librsvg
    - libtiff
    - libxml2
    - llvmdev==5
    - lz4
    - lz4-c
    # - mysql
    - numpy
    - openssl
    - pcre
    # - postgresql
    - pythia8
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run:
    - compilers
    - {{ pin_compatible('numpy') }}
    - afterimage
    - openblas
    - cfitsio
    # - clangdev={{ clang_version }}
    # - clang_variant * cling_{{ version }}
    - davix
    - fftw
    - freetype
    - giflib
    - gsl
    - gdk-pixbuf
    - krb5  # [osx]
    - libglu  # [linux]
    - libpng
    - librsvg
    - libtiff
    - libxml2
    - lz4
    - lz4-c
    # - mysql
    - metakernel
    - notebook
    - openssl
    - pcre
    # - postgresql
    - pythia8
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run_constrained:
    # Items listed here conflict with ROOT
    # FIXME Add support in ROOT for building with an external cling
    - cling 9999
    - root5 9999

test:
  requires:
    - ipython
  imports:
    - ROOT
    - JupyROOT
  commands:
    - ipython -c 'import JsMVA'
    - root -l -b -q -x
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp++
    # When testing with -e, explicitly set the return code to zero
    - root -b -l -q -x -e '2+3; 0'
    - root -b -l -q -x -e 'gSystem->LoadAllLibraries(); 0'
    - echo ${CONDA_BUILD_SYSROOT}  # [osx]
    # There should be no hard coded references to the SDK
    - "! grep -r ${CONDA_BUILD_SYSROOT} ${CONDA_PREFIX}/lib"  # [osx]
    # Check the thisroot scripts work
    - thisroot.sh
    - thisroot.csh
    - thisroot.fish

about:
  home: https://root.cern/
  license: LGPL-2.1
  license_family: LGPL
  license_file: root-source/LICENSE
  doc_url: https://root.cern/documentation
  dev_url: https://github.com/root-project/root/
  summary: |
      ROOT is a modular scientific software toolkit. It provides all the functionalities needed to deal with big data
      processing, statistical analysis, visualisation and storage. It is mainly written in C++ but integrated with other
      languages such as Python and R.
  description: |
      Almost everything in ROOT should be supported in this Conda package; ROOT was built with lots of options turned
      on. Here are a few things to try:

      * `root`: you can start up a session and see the splash screen; Control-D to exit.
      * `python` followed by `import ROOT` will load PyROOT.
      * `root --notebook` will start a notebook server with a ROOT kernel choice.
      * `rootbrowse` will open a TBrowser session so you can look through files.
      * `root -l -q $ROOTSYS/tutorials/dataframe/df013_InspectAnalysis.C` will run a DataFrame example with an animated plot.
      * `root -b -q -l -n -e "std::cout << TROOT::GetTutorialDir() << std::endl;"` will print the tutorial dir.
      * `root -b -l -q -e 'std::cout << (float) TPython::Eval("1+1") << endl;'` will run Python from C++ ROOT.

      See the post [here](https://iscinumpy.gitlab.io/post/root-conda/) for more information about using this Conda package.

      Caveats
      =======

      General
      -------

      The ROOT package will prepare the required compilers (see below). Everything in Conda is symlinked into
      `$CONDA_PREFIX` if you build things by hand; tools like CMake should find it automatically. The `thisroot.*`
      scripts should not be used. Graphics, `rootbrowse`, etc. all should work.

      Linux
      -----

      On Linux, there really aren't any special caveats, just a few general to Conda itself, and the compilers package.
      When ROOT is in the active environment, `g++` and `$CXX` are the conda compilers, GCC 7.3.

      ROOT was built with and will report `-std=c++17` from `root-config`.


      macOS
      -----

      The caveats on macOS are a bit larger, but have the same reason for existing as on Linux. When ROOT is in the
      active environment, `clang++` and `$CXX` will be the Conda compilers; but those compilers are Clang 4.0 and the
      macOS 10.9 SDK.  You must install the macOS 10.9 SDK, [as mentioned in the conda
      documentation](https://conda.io/projects/conda-build/en/latest/source/compiler-tools.html#macos-sdk), if you want
      to build anything.  And, while normal ROOT and PyROOT are fine, commands like `root MyFile.C+` actively build
      things, so this is probably something many users will want to do. Once the macOS is downloaded and extracted on
      your system, you should set `CONDA_BUILD_SYSROOT` to point to the SDK root location, such as
      `/opt/MacOSX10.9.sdk`. This will not be necessary once ROOT moves to using LLVM 8.

      ROOT does not link to Python directly in order to properly support PyROOT from Python, but has been patched to
      provide the correct behavior to allow PyROOT to also be used from ROOT's C++ command line.

      ROOT was built with and will report `-std=c++1z` from `root-config`.

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - bluehood
    - egpbos
