{% set name = "root" %}
{% set version = "6.16.00" %}
{% set hash = "c8415df5a0ec1619df5da0a2a36d79a47f1cf5927ee66cb5f045b39bb250c79a" %}
{% set variant = "openblas" %}
{% set clang_version = "5.0.0" %}
{% set clang_patches_version = "6.16.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/root-project/root/archive/v{{ version|replace(".","-") }}.tar.gz
  sha256: {{ hash }}
  folder: root-source
  patches:
    - patches/root-6.12.06_cling-runtime-sysroot.patch
    - patches/clang-4.0.0_cxx11.patch  # [osx]
    - patches/root-6.16.xx_allow_setting_clang_version.patch  # [osx]
    - patches/root-6.16.xx_python_mac_os.patch  # [osx]

build:
  number: 0
  skip: True  # [not osx]
  skip: True  # [py27]
  skip: True  # [py36]
  features:
    - blas_{{ variant }}
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=root
    - {{ pin_subpackage('root', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - git
    - pkg-config
  host:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - afterimage
    - openblas
    - cfitsio
    - clangdev={{ clang_version }}
    - clang_variant * cling_{{ clang_patches_version }}
    - davix
    - fftw
    - freetype
    - giflib
    - graphviz
    - gsl
    - krb5  # [osx]
    - libglu  # [linux]
    - libpng
    - libtiff
    - libxml2
    - llvmdev==5
    - lz4
    - lz4-c
    # - mysql
    - numpy
    - openssl
    - pcre
    # - postgresql
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [linux]
    - {{ pin_compatible('numpy') }}
    - afterimage
    - openblas
    - cfitsio
    - clangdev={{ clang_version }}
    - clang_variant * cling_{{ version }}
    - davix
    - fftw
    - freetype
    - giflib
    - graphviz
    - gsl
    - krb5  # [osx]
    - libcxx=4  # [osx]
    - libglu  # [linux]
    - libpng
    - libtiff
    - libxml2
    - lz4
    - lz4-c
    # - mysql
    - openssl
    - pcre
    # - postgresql
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run_constrained:
    # FIXME Add support in ROOT for building with an external cling
    - cling 9999

test:
  requires:
    - ipython
  imports:
    - ROOT
    - JupyROOT
  commands:
    - ipython -c 'import JsMVA'
    - root.exe -b -l -q -e
    - root.exe -b -l -q -e 'gSystem->Load("libGeom")'
    - root -l -b -q -x
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp++
    # When testing with -e, explicitly set the return code to zero
    - root -b -l -q -x -e '2+3; 0'
    - root -b -l -q -x -e 'gSystem->LoadAllLibraries(); 0'

about:
  home: https://root.cern/
  license: LGPL-2.1
  license_family: LGPL
  license_file: root-source/LICENSE
  summary: 'Data Analysis Framework'
  doc_url: https://root.cern/documentation
  dev_url: https://github.com/root-project/root/

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - bluehood
    - egpbos
