{% set version = "6.18.00" %}
{% set build_number = "18" %}
{% set hash = "ee11687172a5d692a082ebfbeea4e0d5fb2f65db88968c0327d10793561c2c1b" %}
{% set clang_version = "5.0.0" %}
{% set clang_patches_version = "6.16.00" %}

# WARNING: This is not a good example of a how a conda forge recipe should look

# Macros MUST come before "package:" else the outputs fail to render
{% macro build_dependencies() %}
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  - {{ compiler('fortran') }}
  - cmake
  - git
  - pkg-config
  - sed
  # Required for OpenGL support
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#libgl
  - {{ cdt('mesa-libgl-devel') }}  # [linux]
  - {{ cdt('mesa-dri-drivers') }}  # [linux]
  - {{ cdt('libselinux') }}  # [linux]
  - {{ cdt('libxdamage') }}  # [linux]
  - {{ cdt('libxxf86vm') }}  # [linux]
{% endmacro -%}

{% macro host_dependencies() %}
  - libblas
  - libcblas
  - {{ compiler('c') }}  # [linux]
  - {{ compiler('cxx') }}  # [linux]
  - {{ compiler('fortran') }}  # [linux]
  - numpy
  - afterimage
  - cfitsio
  - clangdev={{ clang_version }}
  - clang_variant * cling_{{ clang_patches_version }}
  - davix >=0.7.2
  - fftw
  - freetype
  - gdk-pixbuf
  - giflib
  - glew
  - gsl
  - krb5  # [osx]
  - libglu  # [linux]
  - libpng
  - librsvg
  - libtiff
  - libxml2
  - llvmdev==5
  - lz4-c
  # - mysql
  - openssl
  - pcre
  # - postgresql
  - pythia8
  - python
  - qt
  - sqlite
  - tbb
  - tbb-devel
  - vdt
  - xorg-libx11  # [linux]
  - xorg-libxau  # [linux]
  - xorg-libxcursor  # [linux]
  - xorg-libxext  # [linux]
  - xorg-libxfixes  # [linux]
  - xorg-libxft  # [linux]
  - xorg-libxpm  # [linux]
  - xrootd
  - xz
  # FIXME: The generated allDict.cxx.pch is dependent on version of the C++ headers used
  - {{ pin_compatible('libcxx', min_pin='x', max_pin='x') }}
{% endmacro -%}

{% macro test_commands() %}
  - root -l -b -q -x
  - root -l -b -q -x test.cpp
  # When testing with -e, explicitly set the return code to zero
  - root -b -l -q -x -e '2+3; 0'
  - root -b -l -q -x -e 'gSystem->LoadAllLibraries(); 0'
  - echo ${CONDA_BUILD_SYSROOT}  # [osx]
  # # There should be no hard coded references to the SDK
  # Check the thisroot scripts work
  - thisroot.sh
  - thisroot.csh
  - thisroot.fish
  # Test if OpenGL is working
  - root -b -l -q -x -e 'gStyle->SetCanvasPreferGL(kTRUE); c = new TCanvas(); if (!c->UseGL()) { throw std::runtime_error("OpenGL does not appear to be working"); }'
  # This test will fail due to lack of graphics support but try it anyway
  # It should exit with "TEveException: TEveManager::Create ROOT is running in batch mode."
  - root -b -l -q -x "${ROOTSYS}/tutorials/eve/geom_lhcb.C" || true
  # This tutorial uses davix to access a ROOT file over HTTP
  - root -b -l -q -x "${ROOTSYS}/tutorials/tree/run_h1analysis.C"
{% endmacro -%}

package:
  name: root
  version: {{ version }}

source:
{%- if "ROOT_JENKINS_GIT_REV" in os.environ %}
  git_url: {{ os.environ.get("ROOT_JENKINS_GIT_URL", "https://github.com/root-project/root.git") }}
  git_rev: {{ os.environ["ROOT_JENKINS_GIT_REV"] }}
{%- else %}
  url: https://github.com/root-project/root/archive/v{{ version|replace(".","-") }}.tar.gz
  sha256: {{ hash }}
{%- endif %}
  folder: root-source
  patches:
    - patches/root-6.18.02-dont-use-cmake-cxx-standard.patch
    - patches/root-6.18.02-force-search-of-build-related-files.patch
    - patches/root-x.xx.xx_cling-runtime-sysroot.patch
    - patches/root-x.xx.xx_python_mac_os.patch  # [osx]
    - patches/root-x.xx.xx-copy-abspath-headers.patch  # [osx]
    - patches/root-x.xx.xx-osx-remove-hardcoded-sysroot.patch  # [osx]

build:
  number: {{ build_number }}
  skip: True  # [win]

# Required for conda to generate the correct build matrix
requirements:
  host: {{- build_dependencies()|replace("\n  ", "\n    ") }}
  host: {{- host_dependencies()|replace("\n  ", "\n    ") }}

outputs:
  - name: root-dependencies
    build:
      number: {{ build_number }}
      skip: True  # [win]
      script: echo "Minimal build script is required for conda to set RECIPE_DIR"
      run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=root
        - {{ pin_subpackage('root-dependencies', max_pin='x.x.x') }}
    requirements:
      # Include the host dependencies so we pick up any pinning and run_exports
      host: {{- host_dependencies()|replace("\n  ", "\n        ") }}
      run:
        - {{ pin_compatible('numpy') }}
        - cfitsio
        - fftw
        - gdk-pixbuf
        - glew
        - graphviz
        - libglu  # [linux]
        - librsvg
        - pythia8
        - python
        - tbb-devel
        - xorg-libx11  # [linux]
        - xorg-libxau  # [linux]
        - xorg-libxcursor  # [linux]
        - xorg-libxext  # [linux]
        - xorg-libxft  # [linux]
        - xorg-libxpm  # [linux]
        # FIXME: Required to ensure a consistent etc/allDict.cxx.pch
        - {{ pin_compatible('libcxx', min_pin='x', max_pin='x') }}
    test:
      commands:
        - echo "Testing is performed in the root_base and root outputs"

  # An underscore is required here to ensure it is built after root-dependencies (reqired for testing)
  - name: root_base
    build:
      number: {{ build_number }}
      skip: True  # [win]
      script:
        - find ${PREFIX}/bin -type f -maxdepth 1 > ${SRC_DIR}/initial-filelist.txt
        - cp -rp ${PREFIX}/bin ${SRC_DIR}/initial-bin-dir
        # Copy the new files in ${PREFIX}/bin to a dedicated directory
        - ${RECIPE_DIR}/build_root-base.sh
        - mkdir ${SRC_DIR}/root-binaries/
        - |
          find ${PREFIX}/bin -type f -maxdepth 1 -exec \
            bash -c 'fn={}; if grep --quiet "^$fn\$" "${SRC_DIR}/initial-filelist.txt"; then echo "Skipping $fn"; else echo "Found new file $fn"; mv "$fn" "${SRC_DIR}/root-binaries/"; fi' \;
      run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=root
        - {{ pin_subpackage('root_base', max_pin='x.x.x') }}
      ignore_prefix_files:
        # FIXME: Figure out how to correct the paths in the PCH
        - etc/allDict.cxx.pch
      # Taken from "conda render ./recipe/ -m .ci_support/osx_python3.7.yaml"
      # Sorted and commented run_exports that we want to keep
      # TODO: This will need updating occasionally
      ignore_run_exports:
        # - afterimage
        # - davix
        # - freetype
        - giflib
        - gsl
        - krb5
        # - libblas
        # - libcblas
        # - libcxx
        # - libgfortran
        # - libpng
        # - libtiff
        # - libxml2
        # - lz4-c
        # - openssl
        # - pcre
        - qt
        - sqlite
        # - tbb
        # - vdt
        # - xrootd
        # - xz
    requirements:
      build: {{- build_dependencies()|replace("\n  ", "\n        ") }}
      host: {{- host_dependencies()|replace("\n  ", "\n        ") }}
      run:
        # FIXME: Required to ensure a consistent etc/allDict.cxx.pch
        - {{ pin_compatible('libcxx', min_pin='x', max_pin='x') }}
      run_constrained:
        # Items listed here conflict with ROOT
        # FIXME Add support in ROOT for building with an external cling
        - cling 9999
        - root5 9999
    test:
      commands:
        - echo "Tested in other outputs"

  - name: root-binaries
    build:
      number: {{ build_number }}
      skip: True  # [win]
      script:
        # Copy the executables back into ${PREFIX}/bin
        # This is done to avoid users getting broken binaries from root_base
        - mkdir -p ${PREFIX}/bin
        - ls ${PREFIX}/bin/
        - cp -rp ${SRC_DIR}/root-binaries/* ${PREFIX}/bin/
        - ls ${PREFIX}/bin/
    requirements:
      build: {{- build_dependencies()|replace("\n  ", "\n        ") }}
      host: {{- host_dependencies()|replace("\n  ", "\n        ") }}
        - {{ pin_subpackage('root_base', exact=True) }}
      run:
        - {{ pin_subpackage('root_base', exact=True) }}
    test:
      files:
        - test.cpp
      requires:
        - root-dependencies {{ version }} *_{{ build_number }}
      commands: {{- test_commands()|replace("\n  ", "\n        ") }}

  - name: root
    build:
      number: {{ build_number }}
      skip: True  # [win]
      script:
        - pwd
        - ls
        - echo "Minimal build script is required for conda to set RECIPE_DIR"
    requirements:
      host:
        - python
      run:
        - python
        - compilers  # This package is hostile to how conda-build manages compilers
        - metakernel
        - notebook
        - {{ pin_subpackage('root_base', exact=True) }}
        - {{ pin_subpackage('root-binaries', exact=True) }}
        - {{ pin_subpackage('root-dependencies', exact=True) }}
    test:
      files:
        - test.cpp
      requires:
        - ipython
      imports:
        - ROOT
        - JupyROOT
      commands: {{- test_commands()|replace("\n  ", "\n        ") }}
        - ipython -c 'import JsMVA'
        # This command only works if the compilers are available
        - root -l -b -q -x test.cpp++

about:
  home: https://root.cern/
  license: LGPL-2.1
  license_family: LGPL
  license_file: root-source/LICENSE
  doc_url: https://root.cern/documentation
  dev_url: https://github.com/root-project/root/
  summary: |
      ROOT is a modular scientific software toolkit. It provides all the functionalities needed to deal with big data
      processing, statistical analysis, visualisation and storage. It is mainly written in C++ but integrated with other
      languages such as Python and R.
  description: |
      Almost everything in ROOT should be supported in this Conda package; ROOT was built with lots of options turned
      on. Here are a few things to try:

      * `root`: you can start up a session and see the splash screen; Control-D to exit.
      * `python` followed by `import ROOT` will load PyROOT.
      * `root --notebook` will start a notebook server with a ROOT kernel choice.
      * `rootbrowse` will open a TBrowser session so you can look through files.
      * `root -l -q $ROOTSYS/tutorials/dataframe/df013_InspectAnalysis.C` will run a DataFrame example with an animated plot.
      * `root -b -q -l -n -e "std::cout << TROOT::GetTutorialDir() << std::endl;"` will print the tutorial dir.
      * `root -b -l -q -e 'std::cout << (float) TPython::Eval("1+1") << endl;'` will run Python from C++ ROOT.

      See the post [here](https://iscinumpy.gitlab.io/post/root-conda/) for more information about using this Conda package.

      Caveats
      =======

      General
      -------

      The ROOT package will prepare the required compilers (see below). Everything in Conda is symlinked into
      `$CONDA_PREFIX` if you build things by hand; tools like CMake should find it automatically. The `thisroot.*`
      scripts should not be used. Graphics, `rootbrowse`, etc. all should work. OpenGL is enabled.

      There is also a `root_base` package, with minimal dependecies, that libraries should dependend on this to avoid
      having a runtime dependency on the `compilers` package. In most cases users should use the `root` package directly.

      Linux
      -----

      On Linux, there really aren't any special caveats, just a few general to Conda itself, and the compilers package.
      When ROOT is in the active environment, `g++` and `$CXX` are the conda compilers, GCC 7.3.

      ROOT was built with and will report `-std=c++17` from `root-config`.


      macOS
      -----

      The caveats on macOS are a bit larger, but have the same reason for existing as on Linux. When ROOT is in the
      active environment, `clang++` and `$CXX` will be the Conda compilers; but those compilers are Clang 4.0 and the
      macOS 10.9 SDK.  You must install the macOS 10.9 SDK, [as mentioned in the conda
      documentation](https://conda.io/projects/conda-build/en/latest/source/compiler-tools.html#macos-sdk), if you want
      to build anything.  And, while normal ROOT and PyROOT are fine, commands like `root MyFile.C+` actively build
      things, so this is probably something many users will want to do. Once the macOS is downloaded and extracted on
      your system, you should set `CONDA_BUILD_SYSROOT` to point to the SDK root location, such as
      `/opt/MacOSX10.9.sdk`. This will not be necessary once ROOT moves to using LLVM 8.

      ROOT does not link to Python directly in order to properly support PyROOT from Python, but has been patched to
      provide the correct behavior to allow PyROOT to also be used from ROOT's C++ command line.

      ROOT was built with and will report `-std=c++1z` from `root-config`.

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - bluehood
    - egpbos
