{% set version = "6.18.04" %}
{% set build_number = 26 %}

package:
  name: root
  version: {{ version }}

build:
  skip: True  # [win]
  script:
    - ${RECIPE_DIR}/build_root-base.sh

requirements:
  host:
    - python
    - afterimage
  run:
    - python
