azure:
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
provider:
  linux_aarch64: travis
  linux_ppc64le: travis
  osx_arm64: osx_64
test_on_native_only: true
