azure:
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  osx_arm64: osx_64
os_version:
  linux_64: cos7
test_on_native_only: true
bot:
  abi_migration_branches:
    - 6.24
