# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "root-feedstock"
version = "3.52.0"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/root-feedstock"
authors = ["@conda-forge/root"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build root-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_python3.10.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.10.____cpython.yaml"
description = "Build root-feedstock with variant linux_64_python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.10.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_64_python3.10.____cpython"
[tasks."build-linux_64_python3.11.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.11.____cpython.yaml"
description = "Build root-feedstock with variant linux_64_python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.11.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_64_python3.11.____cpython"
[tasks."build-linux_64_python3.12.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.12.____cpython.yaml"
description = "Build root-feedstock with variant linux_64_python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-linux_64_python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.12.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_64_python3.12.____cpython"
[tasks."build-linux_64_python3.13.____cp313"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python3.13.____cp313.yaml"
description = "Build root-feedstock with variant linux_64_python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-linux_64_python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python3.13.____cp313.yaml"
description = "List contents of root-feedstock packages built for variant linux_64_python3.13.____cp313"
[tasks."build-linux_aarch64_python3.10.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_python3.10.____cpython.yaml"
description = "Build root-feedstock with variant linux_aarch64_python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_python3.10.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_aarch64_python3.10.____cpython"
[tasks."build-linux_aarch64_python3.11.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_python3.11.____cpython.yaml"
description = "Build root-feedstock with variant linux_aarch64_python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_python3.11.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_aarch64_python3.11.____cpython"
[tasks."build-linux_aarch64_python3.12.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_python3.12.____cpython.yaml"
description = "Build root-feedstock with variant linux_aarch64_python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-linux_aarch64_python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_python3.12.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_aarch64_python3.12.____cpython"
[tasks."build-linux_aarch64_python3.13.____cp313"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_python3.13.____cp313.yaml"
description = "Build root-feedstock with variant linux_aarch64_python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-linux_aarch64_python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_python3.13.____cp313.yaml"
description = "List contents of root-feedstock packages built for variant linux_aarch64_python3.13.____cp313"
[tasks."build-linux_ppc64le_python3.10.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_python3.10.____cpython.yaml"
description = "Build root-feedstock with variant linux_ppc64le_python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_python3.10.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_ppc64le_python3.10.____cpython"
[tasks."build-linux_ppc64le_python3.11.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_python3.11.____cpython.yaml"
description = "Build root-feedstock with variant linux_ppc64le_python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_python3.11.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_ppc64le_python3.11.____cpython"
[tasks."build-linux_ppc64le_python3.12.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_python3.12.____cpython.yaml"
description = "Build root-feedstock with variant linux_ppc64le_python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_python3.12.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant linux_ppc64le_python3.12.____cpython"
[tasks."build-linux_ppc64le_python3.13.____cp313"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_python3.13.____cp313.yaml"
description = "Build root-feedstock with variant linux_ppc64le_python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_python3.13.____cp313.yaml"
description = "List contents of root-feedstock packages built for variant linux_ppc64le_python3.13.____cp313"
[tasks."build-osx_64_python3.10.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.10.____cpython.yaml"
description = "Build root-feedstock with variant osx_64_python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-osx_64_python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.10.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_64_python3.10.____cpython"
[tasks."build-osx_64_python3.11.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.11.____cpython.yaml"
description = "Build root-feedstock with variant osx_64_python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-osx_64_python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.11.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_64_python3.11.____cpython"
[tasks."build-osx_64_python3.12.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.12.____cpython.yaml"
description = "Build root-feedstock with variant osx_64_python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-osx_64_python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.12.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_64_python3.12.____cpython"
[tasks."build-osx_64_python3.13.____cp313"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_python3.13.____cp313.yaml"
description = "Build root-feedstock with variant osx_64_python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-osx_64_python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_python3.13.____cp313.yaml"
description = "List contents of root-feedstock packages built for variant osx_64_python3.13.____cp313"
[tasks."build-osx_arm64_python3.10.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.10.____cpython.yaml"
description = "Build root-feedstock with variant osx_arm64_python3.10.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_python3.10.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.10.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_arm64_python3.10.____cpython"
[tasks."build-osx_arm64_python3.11.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.11.____cpython.yaml"
description = "Build root-feedstock with variant osx_arm64_python3.11.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_python3.11.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.11.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_arm64_python3.11.____cpython"
[tasks."build-osx_arm64_python3.12.____cpython"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.12.____cpython.yaml"
description = "Build root-feedstock with variant osx_arm64_python3.12.____cpython directly (without setup scripts)"
[tasks."inspect-osx_arm64_python3.12.____cpython"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.12.____cpython.yaml"
description = "List contents of root-feedstock packages built for variant osx_arm64_python3.12.____cpython"
[tasks."build-osx_arm64_python3.13.____cp313"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_python3.13.____cp313.yaml"
description = "Build root-feedstock with variant osx_arm64_python3.13.____cp313 directly (without setup scripts)"
[tasks."inspect-osx_arm64_python3.13.____cp313"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_python3.13.____cp313.yaml"
description = "List contents of root-feedstock packages built for variant osx_arm64_python3.13.____cp313"

[feature.smithy.dependencies]
conda-smithy = "*"
shellcheck = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
